# Generated by Django 4.2.5 on 2023-10-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memu',
            name='cover',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
